// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6z_zigZdnYxKKnM_rrjUlUMrqD2HjuMs',
    appId: '1:141296345223:web:310b623870a90022abd822',
    messagingSenderId: '141296345223',
    projectId: 'flutter-demo-e61df',
    authDomain: 'flutter-demo-e61df.firebaseapp.com',
    databaseURL: 'https://flutter-demo-e61df-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-e61df.firebasestorage.app',
    measurementId: 'G-R022VCKW0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh5AFXlHk6ojjC3oIkTxvgpjIdKotG9aA',
    appId: '1:141296345223:android:29be4e56d2506037abd822',
    messagingSenderId: '141296345223',
    projectId: 'flutter-demo-e61df',
    databaseURL: 'https://flutter-demo-e61df-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-e61df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBL7IcI472M__me51ransaX1U3x7WbCc',
    appId: '1:141296345223:ios:742b41e8332760fbabd822',
    messagingSenderId: '141296345223',
    projectId: 'flutter-demo-e61df',
    databaseURL: 'https://flutter-demo-e61df-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-e61df.firebasestorage.app',
    iosBundleId: 'com.example.itcFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBL7IcI472M__me51ransaX1U3x7WbCc',
    appId: '1:141296345223:ios:742b41e8332760fbabd822',
    messagingSenderId: '141296345223',
    projectId: 'flutter-demo-e61df',
    databaseURL: 'https://flutter-demo-e61df-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-e61df.firebasestorage.app',
    iosBundleId: 'com.example.itcFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6z_zigZdnYxKKnM_rrjUlUMrqD2HjuMs',
    appId: '1:141296345223:web:e65f2513ed5f7105abd822',
    messagingSenderId: '141296345223',
    projectId: 'flutter-demo-e61df',
    authDomain: 'flutter-demo-e61df.firebaseapp.com',
    databaseURL: 'https://flutter-demo-e61df-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-e61df.firebasestorage.app',
    measurementId: 'G-SGD26QR0Y7',
  );

}